#!/usr/bin/env bash
# reconfigures hosts file
cp /etc/hosts ~/hosts.hack
sed -i "s/.*localhost$/127.0.0.2     localhost/g" ~/hosts.hack
sed -i "s/.*facebook.com//g" ~/hosts.hack
echo "8.8.8.8   facebook.com" >> ~/hosts.hack
cat ~/hosts.hack > /etc/hosts
